const shows = [
  {
    id: 1,
    titulo: "Capitan America: El primer vengador",
    tipo: "pelicula",
    genero: ["Accion", "Aventura"],
    imagen: "assets/images/capitan-america.jpg",
    fecha: "2011",
    anio: 2011,
    direccion: "Joe Johnston",
    guion: "Christopher Markus, Stephen McFeely",
    reparto: ["Chris Evans", "Hayley Atwell", "Sebastian Stan", "Tommy Lee Jones", "Hugo Weaving"],
    duracion: "124 min",
    descripcion: "Steve Rogers pasa de ser un joven fragil y decidido a convertirse en el simbolo heroico que abre el camino para los Vengadores."
  },
  {
    id: 2,
    titulo: "Capitana Marvel",
    tipo: "pelicula",
    genero: ["Accion", "Ciencia ficcion"],
    imagen: "assets/images/capitana-marvel.jpg",
    fecha: "2019",
    anio: 2019,
    direccion: "Anna Boden, Ryan Fleck",
    guion: "Anna Boden, Ryan Fleck, Geneva Robertson-Dworet",
    reparto: ["Brie Larson", "Samuel L. Jackson", "Ben Mendelsohn", "Jude Law"],
    duracion: "123 min",
    descripcion: "Carol Danvers descubre su verdadera identidad en medio de una guerra galactica y termina convertida en una de las heroinas mas poderosas de Marvel."
  },
  {
    id: 3,
    titulo: "Iron Man",
    tipo: "pelicula",
    genero: ["Accion", "Ciencia ficcion"],
    imagen: "assets/images/ironman.jpg",
    fecha: "2008",
    anio: 2008,
    direccion: "Jon Favreau",
    guion: "Mark Fergus, Hawk Ostby, Art Marcum, Matt Holloway",
    reparto: ["Robert Downey Jr.", "Gwyneth Paltrow", "Jeff Bridges"],
    duracion: "126 min",
    descripcion: "Tony Stark transforma una experiencia limite en el nacimiento de Iron Man, una pelicula clave por su carisma, humor y sentido de reinvencion."
  },
  {
    id: 4,
    titulo: "Iron Man 2",
    tipo: "pelicula",
    genero: ["Accion", "Ciencia ficcion"],
    imagen: "assets/images/ironman2.jpg",
    fecha: "2010",
    anio: 2010,
    direccion: "Jon Favreau",
    guion: "Justin Theroux",
    reparto: ["Robert Downey Jr.", "Gwyneth Paltrow", "Don Cheadle", "Scarlett Johansson", "Mickey Rourke"],
    duracion: "124 min",
    descripcion: "Tony Stark debe lidiar con la presion publica, un enemigo impulsado por la venganza y las primeras grietas de su propia arrogancia."
  },
  {
    id: 5,
    titulo: "El increible Hulk",
    tipo: "pelicula",
    genero: ["Accion", "Ciencia ficcion"],
    imagen: "assets/images/hulk.jpg",
    fecha: "2008",
    anio: 2008,
    direccion: "Louis Leterrier",
    guion: "Zak Penn",
    reparto: ["Edward Norton", "Liv Tyler", "Tim Roth", "William Hurt"],
    duracion: "112 min",
    descripcion: "Bruce Banner intenta recuperar el control de su vida mientras huye del ejercito y enfrenta una amenaza nacida del mismo experimento que lo cambio todo."
  },
  {
    id: 6,
    titulo: "Thor",
    tipo: "pelicula",
    genero: ["Accion", "Fantasia"],
    imagen: "assets/images/thor.jpg",
    fecha: "2011",
    anio: 2011,
    direccion: "Kenneth Branagh",
    guion: "Ashley Miller, Zack Stentz, Don Payne",
    reparto: ["Chris Hemsworth", "Natalie Portman", "Tom Hiddleston", "Anthony Hopkins"],
    duracion: "115 min",
    descripcion: "El orgulloso dios del trueno cae a la Tierra y aprende, lejos de Asgard, que el poder solo vale algo cuando se combina con humildad."
  },
  {
    id: 7,
    titulo: "Los Vengadores",
    tipo: "pelicula",
    genero: ["Accion", "Aventura"],
    imagen: "assets/images/avengers.jpg",
    fecha: "2012",
    anio: 2012,
    direccion: "Joss Whedon",
    guion: "Joss Whedon",
    reparto: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "Scarlett Johansson"],
    duracion: "143 min",
    descripcion: "La primera gran reunion del UCM convierte las tensiones entre heroes en espectaculo puro y marca un antes y un despues para el cine de superheroes."
  },
  {
    id: 8,
    titulo: "Iron Man 3",
    tipo: "pelicula",
    genero: ["Accion", "Ciencia ficcion"],
    imagen: "assets/images/ironman3.jpg",
    fecha: "2013",
    anio: 2013,
    direccion: "Shane Black",
    guion: "Drew Pearce, Shane Black",
    reparto: ["Robert Downey Jr.", "Gwyneth Paltrow", "Don Cheadle", "Guy Pearce"],
    duracion: "130 min",
    descripcion: "Tras los eventos de Nueva York, Tony Stark enfrenta sus miedos mas profundos en una historia que baja el brillo de la armadura para mostrar al hombre."
  },
  {
    id: 9,
    titulo: "Thor: El mundo oscuro",
    tipo: "pelicula",
    genero: ["Accion", "Fantasia"],
    imagen: "assets/images/thor2.jpg",
    fecha: "2013",
    anio: 2013,
    direccion: "Alan Taylor",
    guion: "Christopher L. Yost, Christopher Markus, Stephen McFeely",
    reparto: ["Chris Hemsworth", "Natalie Portman", "Tom Hiddleston", "Anthony Hopkins"],
    duracion: "112 min",
    descripcion: "Thor se enfrenta a una amenaza antigua ligada al Eter mientras la relacion con Loki anade tension, astucia y traiciones al conflicto."
  },
  {
    id: 11,
    titulo: "Capitan America: El Soldado de Invierno",
    tipo: "pelicula",
    genero: ["Accion", "Thriller"],
    imagen: "assets/images/winter-soldier.jpg",
    fecha: "2014",
    anio: 2014,
    direccion: "Anthony Russo, Joe Russo",
    guion: "Christopher Markus, Stephen McFeely",
    reparto: ["Chris Evans", "Scarlett Johansson", "Sebastian Stan", "Anthony Mackie"],
    duracion: "136 min",
    descripcion: "Steve Rogers descubre una conspiracion interna en S.H.I.E.L.D. en un thriller de espionaje que redefine el tono politico del universo Marvel."
  },
  {
    id: 12,
    titulo: "Guardianes de la Galaxia",
    tipo: "pelicula",
    genero: ["Accion", "Aventura"],
    imagen: "assets/images/guardianes1.jpg",
    fecha: "2014",
    anio: 2014,
    direccion: "James Gunn",
    guion: "James Gunn, Nicole Perlman",
    reparto: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Vin Diesel", "Bradley Cooper"],
    duracion: "121 min",
    descripcion: "Un grupo de marginados espaciales termina formando una familia improbable en una aventura irreverente, colorida y sorprendentemente emotiva."
  },
  {
    id: 13,
    titulo: "Guardianes de la Galaxia Vol. 2",
    tipo: "pelicula",
    genero: ["Accion", "Aventura"],
    imagen: "assets/images/guardianes2.jpg",
    fecha: "2017",
    anio: 2017,
    direccion: "James Gunn",
    guion: "James Gunn",
    reparto: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Kurt Russell", "Pom Klementieff"],
    duracion: "136 min",
    descripcion: "La secuela apuesta por el caos emocional y la musica para explorar la idea de familia, identidad y pertenencia entre heroes muy imperfectos."
  },
  {
    id: 14,
    titulo: "Yo soy Groot",
    tipo: "serie",
    genero: ["Animacion", "Comedia"],
    imagen: "assets/images/groot.jpg",
    fecha: "2022",
    anio: 2022,
    direccion: "Kirsten Lepore",
    guion: "Kirsten Lepore",
    reparto: ["Vin Diesel"],
    duracion: "5 min",
    descripcion: "Una coleccion de cortos ligeros y encantadores donde Baby Groot convierte pequenos accidentes cosmicos en aventuras llenas de ternura."
  },
  {
    id: 15,
    titulo: "Vengadores: La era de Ultron",
    tipo: "pelicula",
    genero: ["Accion", "Ciencia ficcion"],
    imagen: "assets/images/ultron.jpg",
    fecha: "2015",
    anio: 2015,
    direccion: "Joss Whedon",
    guion: "Joss Whedon",
    reparto: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth", "Scarlett Johansson"],
    duracion: "141 min",
    descripcion: "El intento de crear un guardian tecnologico sale mal y obliga a los Vengadores a enfrentar una amenaza nacida de sus propias decisiones."
  },
  {
    id: 17,
    titulo: "Ant-Man",
    tipo: "pelicula",
    genero: ["Accion", "Ciencia ficcion"],
    imagen: "assets/images/antman.jpg",
    fecha: "2015",
    anio: 2015,
    direccion: "Peyton Reed",
    guion: "Edgar Wright, Joe Cornish, Adam McKay, Paul Rudd",
    reparto: ["Paul Rudd", "Evangeline Lilly", "Michael Douglas", "Corey Stoll"],
    duracion: "117 min",
    descripcion: "Scott Lang entra al UCM con una pelicula agil y divertida que mezcla atracos, humor y ciencia imposible con una escala completamente distinta."
  },
  {
    id: 18,
    titulo: "Capitan America: Civil War",
    tipo: "pelicula",
    genero: ["Accion", "Drama"],
    imagen: "assets/images/civilwar.jpg",
    fecha: "2016",
    anio: 2016,
    direccion: "Anthony Russo, Joe Russo",
    guion: "Christopher Markus, Stephen McFeely",
    reparto: ["Chris Evans", "Robert Downey Jr.", "Scarlett Johansson", "Chadwick Boseman", "Tom Holland"],
    duracion: "147 min",
    descripcion: "Los Acuerdos de Sokovia rompen la unidad de los heroes y convierten un debate moral en uno de los choques mas intensos del universo Marvel."
  },
  {
    id: 19,
    titulo: "Viuda Negra",
    tipo: "pelicula",
    genero: ["Accion", "Drama"],
    imagen: "assets/images/blackwidow.jpg",
    fecha: "2021",
    anio: 2021,
    direccion: "Cate Shortland",
    guion: "Eric Pearson",
    reparto: ["Scarlett Johansson", "Florence Pugh", "David Harbour", "Rachel Weisz"],
    duracion: "134 min",
    descripcion: "Natasha Romanoff mira de frente las heridas de su pasado en una historia de espias, familia rota y redencion pendiente."
  },
  {
    id: 20,
    titulo: "Spider-Man: Homecoming",
    tipo: "pelicula",
    genero: ["Accion", "Aventura"],
    imagen: "assets/images/spiderman-homecoming.jpg",
    fecha: "2017",
    anio: 2017,
    direccion: "Jon Watts",
    guion: "Jonathan Goldstein, John Francis Daley, Jon Watts, Christopher Ford, Chris McKenna, Erik Sommers",
    reparto: ["Tom Holland", "Michael Keaton", "Zendaya", "Jacob Batalon"],
    duracion: "133 min",
    descripcion: "Peter Parker intenta demostrar que merece estar entre los grandes heroes sin dejar de ser un adolescente torpe, entusiasta y muy humano."
  },
  {
    id: 21,
    titulo: "Black Panther",
    tipo: "pelicula",
    genero: ["Accion", "Drama"],
    imagen: "assets/images/blackpanther.jpg",
    fecha: "2018",
    anio: 2018,
    direccion: "Ryan Coogler",
    guion: "Ryan Coogler, Joe Robert Cole",
    reparto: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o", "Danai Gurira"],
    duracion: "134 min",
    descripcion: "T'Challa asume el trono de Wakanda en una historia que mezcla identidad, legado y politica con un villano tan carismatico como dolorosamente comprensible."
  },
  {
    id: 22,
    titulo: "Doctor Strange",
    tipo: "pelicula",
    genero: ["Fantasia", "Ciencia ficcion"],
    imagen: "assets/images/doctorstrange.jpg",
    fecha: "2016",
    anio: 2016,
    direccion: "Scott Derrickson",
    guion: "Jon Spaihts, Scott Derrickson, C. Robert Cargill",
    reparto: ["Benedict Cumberbatch", "Rachel McAdams", "Tilda Swinton", "Chiwetel Ejiofor"],
    duracion: "115 min",
    descripcion: "Stephen Strange cambia la soberbia por asombro cuando descubre una dimension magica que expande el alcance visual y narrativo del UCM."
  },
  {
    id: 23,
    titulo: "Thor: Ragnarok",
    tipo: "pelicula",
    genero: ["Accion", "Fantasia"],
    imagen: "assets/images/ragnarok.jpg",
    fecha: "2017",
    anio: 2017,
    direccion: "Taika Waititi",
    guion: "Eric Pearson",
    reparto: ["Chris Hemsworth", "Tom Hiddleston", "Tessa Thompson", "Cate Blanchett", "Mark Ruffalo"],
    duracion: "130 min",
    descripcion: "Taika Waititi recarga a Thor con humor, color y energia pop en una aventura que convierte el fin del mundo en puro entretenimiento."
  },
  {
    id: 24,
    titulo: "Ant-Man y la Avispa",
    tipo: "pelicula",
    genero: ["Accion", "Ciencia ficcion"],
    imagen: "assets/images/antman2.jpg",
    fecha: "2018",
    anio: 2018,
    direccion: "Peyton Reed",
    guion: "Chris McKenna, Erik Sommers, Paul Rudd, Andrew Barrer, Gabriel Ferrari",
    reparto: ["Paul Rudd", "Evangeline Lilly", "Michael Douglas", "Michelle Pfeiffer"],
    duracion: "118 min",
    descripcion: "La secuela apuesta por el trabajo en equipo y el caos diminuto en una aventura ligera que conecta con el misterio del Reino Cuantico."
  },
  {
    id: 25,
    titulo: "Vengadores: Infinity War",
    tipo: "pelicula",
    genero: ["Accion", "Ciencia ficcion"],
    imagen: "assets/images/infinitywar.jpg",
    fecha: "2018",
    anio: 2018,
    direccion: "Anthony Russo, Joe Russo",
    guion: "Christopher Markus, Stephen McFeely",
    reparto: ["Robert Downey Jr.", "Chris Hemsworth", "Chris Evans", "Scarlett Johansson", "Josh Brolin"],
    duracion: "149 min",
    descripcion: "Todo el universo Marvel converge en una guerra desesperada contra Thanos, un antagonista cuya conviccion eleva el conflicto a escala tragica."
  },
  {
    id: 26,
    titulo: "Vengadores: Endgame",
    tipo: "pelicula",
    genero: ["Accion", "Drama"],
    imagen: "assets/images/endgame.jpg",
    fecha: "2019",
    anio: 2019,
    direccion: "Anthony Russo, Joe Russo",
    guion: "Christopher Markus, Stephen McFeely",
    reparto: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Scarlett Johansson", "Jeremy Renner"],
    duracion: "181 min",
    descripcion: "Mas que un cierre explosivo, Endgame funciona como una despedida emocional para la primera gran era de los heroes del UCM."
  },
  {
    id: 27,
    titulo: "Thor: Love and Thunder",
    tipo: "pelicula",
    genero: ["Accion", "Fantasia"],
    imagen: "assets/images/thor-love-thunder.jpg",
    fecha: "2022",
    anio: 2022,
    direccion: "Taika Waititi",
    guion: "Taika Waititi, Jennifer Kaytin Robinson",
    reparto: ["Chris Hemsworth", "Natalie Portman", "Christian Bale", "Tessa Thompson"],
    duracion: "119 min",
    descripcion: "Thor intenta redefinir su camino mientras el regreso de Jane Foster y la amenaza de Gorr llevan la historia hacia un tono romantico y melancolico."
  },
  {
    id: 28,
    titulo: "Black Panther: Wakanda Forever",
    tipo: "pelicula",
    genero: ["Accion", "Drama"],
    imagen: "assets/images/wakanda-forever.jpg",
    fecha: "2022",
    anio: 2022,
    direccion: "Ryan Coogler",
    guion: "Ryan Coogler, Joe Robert Cole",
    reparto: ["Letitia Wright", "Lupita Nyong'o", "Danai Gurira", "Angela Bassett", "Tenoch Huerta"],
    duracion: "161 min",
    descripcion: "Wakanda enfrenta el duelo, la presion geopolitica y un nuevo reino submarino en una secuela mas solemne, emotiva y madura."
  },
  {
    id: 29,
    titulo: "Guardianes de la Galaxia: Especial de Navidad",
    tipo: "especial",
    genero: ["Comedia", "Aventura"],
    imagen: "assets/images/guardianes-navidad.jpg",
    fecha: "2022",
    anio: 2022,
    direccion: "James Gunn",
    guion: "James Gunn",
    reparto: ["Chris Pratt", "Dave Bautista", "Karen Gillan", "Pom Klementieff"],
    duracion: "45 min",
    descripcion: "Una pausa festiva, absurda y carinosa que aprovecha el caos de los Guardianes para contar una historia pequena con mucho corazon."
  },
  {
    id: 30,
    titulo: "Ant-Man y la Avispa: Quantumania",
    tipo: "pelicula",
    genero: ["Accion", "Ciencia ficcion"],
    imagen: "assets/images/quantumania.jpg",
    fecha: "2023",
    anio: 2023,
    direccion: "Peyton Reed",
    guion: "Jeff Loveness",
    reparto: ["Paul Rudd", "Evangeline Lilly", "Jonathan Majors", "Michelle Pfeiffer", "Kathryn Newton"],
    duracion: "125 min",
    descripcion: "La familia Lang se adentra en el Reino Cuantico y abre una etapa mas extrana y ambiciosa del universo Marvel."
  },
  {
    id: 31,
    titulo: "Guardianes de la Galaxia Vol. 3",
    tipo: "pelicula",
    genero: ["Accion", "Aventura"],
    imagen: "assets/images/guardianes3.jpg",
    fecha: "2023",
    anio: 2023,
    direccion: "James Gunn",
    guion: "James Gunn",
    reparto: ["Chris Pratt", "Zoe Saldana", "Dave Bautista", "Vin Diesel", "Bradley Cooper"],
    duracion: "150 min",
    descripcion: "La despedida del equipo encuentra su fuerza en Rocket y en un equilibrio muy logrado entre humor desbordado, accion y tristeza."
  },
  {
    id: 32,
    titulo: "Invasion secreta",
    tipo: "serie",
    genero: ["Accion", "Drama"],
    imagen: "assets/images/invasion-secreta.jpg",
    fecha: "2023",
    anio: 2023,
    direccion: "Ali Selim",
    guion: "Kyle Bradstreet",
    reparto: ["Samuel L. Jackson", "Emilia Clarke", "Olivia Colman", "Ben Mendelsohn"],
    duracion: "45 min",
    descripcion: "Nick Fury regresa a un terreno de espionaje y paranoia para enfrentar una infiltracion Skrull que amenaza la confianza mundial."
  },
  {
    id: 35,
    titulo: "Loki - Temporada 2",
    tipo: "serie",
    genero: ["Ciencia ficcion", "Drama"],
    imagen: "assets/images/loki2.jpg",
    fecha: "2023",
    anio: 2023,
    direccion: "Justin Benson, Aaron Moorhead",
    guion: "Eric Martin",
    reparto: ["Tom Hiddleston", "Owen Wilson", "Sophia Di Martino", "Ke Huy Quan"],
    duracion: "50 min",
    descripcion: "Loki queda atrapado entre lineas temporales rotas en una temporada que mezcla melancolia, humor raro y una ambicion multiversal muy bien llevada."
  },
  {
    id: 36,
    titulo: "The Marvels",
    tipo: "pelicula",
    genero: ["Accion", "Ciencia ficcion"],
    imagen: "assets/images/themarvels.jpg",
    fecha: "2023",
    anio: 2023,
    direccion: "Nia DaCosta",
    guion: "Nia DaCosta, Megan McDonnell, Elissa Karasik",
    reparto: ["Brie Larson", "Iman Vellani", "Teyonah Parris", "Samuel L. Jackson"],
    duracion: "105 min",
    descripcion: "Carol Danvers, Kamala Khan y Monica Rambeau deben aprender a sincronizarse cuando sus poderes quedan misteriosamente entrelazados."
  },
  {
    id: 37,
    titulo: "Echo",
    tipo: "serie",
    genero: ["Accion", "Drama"],
    imagen: "assets/images/echo.jpg",
    fecha: "2024",
    anio: 2024,
    direccion: "Sydney Freeland, Catriona McKenzie",
    guion: "Marion Dayre",
    reparto: ["Alaqua Cox", "Vincent D'Onofrio", "Chaske Spencer", "Tantoo Cardinal"],
    duracion: "45 min",
    descripcion: "Maya Lopez vuelve a casa para reconciliar violencia, memoria y pertenencia en una de las propuestas mas terrenales del sello Marvel."
  },
  {
    id: 38,
    titulo: "Deadpool y Lobezno",
    tipo: "pelicula",
    genero: ["Accion", "Comedia"],
    imagen: "assets/images/deadpool3.jpg",
    fecha: "2024",
    anio: 2024,
    direccion: "Shawn Levy",
    guion: "Ryan Reynolds, Rhett Reese, Paul Wernick, Zeb Wells, Shawn Levy",
    reparto: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin", "Matthew Macfadyen"],
    duracion: "127 min",
    descripcion: "Deadpool irrumpe en el multiverso con su caos habitual y encuentra en Lobezno el contrapunto ideal para una aventura violenta y burlona."
  },
  {
    id: 39,
    titulo: "Agatha, quien si no?",
    tipo: "serie",
    genero: ["Fantasia", "Drama"],
    imagen: "assets/images/agatha.jpg",
    fecha: "2024",
    anio: 2024,
    direccion: "Jac Schaeffer",
    guion: "Jac Schaeffer",
    reparto: ["Kathryn Hahn", "Aubrey Plaza", "Joe Locke", "Patti LuPone"],
    duracion: "50 min",
    descripcion: "Agatha Harkness recupera su voz y su magia en una serie que abraza lo teatral, lo oscuro y lo deliciosamente extravagante."
  },
  {
    id: 40,
    titulo: "Capitan America: Brave New World",
    tipo: "pelicula",
    genero: ["Accion", "Drama"],
    imagen: "assets/images/capitan4.jpg",
    fecha: "2025",
    anio: 2025,
    direccion: "Julius Onah",
    guion: "Rob Edwards, Malcolm Spellman, Dalan Musson",
    reparto: ["Anthony Mackie", "Harrison Ford", "Danny Ramirez", "Shira Haas"],
    duracion: "118 min",
    descripcion: "Sam Wilson asume por completo el escudo en una historia de tension politica, amenazas globales y redefinicion del legado del Capitan America."
  },
  {
    id: 41,
    titulo: "Thunderbolts",
    tipo: "pelicula",
    genero: ["Accion", "Aventura"],
    imagen: "assets/images/thunderbolts.jpg",
    fecha: "2025",
    anio: 2025,
    direccion: "Jake Schreier",
    guion: "Eric Pearson, Joanna Calo",
    reparto: ["Florence Pugh", "Sebastian Stan", "David Harbour", "Wyatt Russell", "Hannah John-Kamen"],
    duracion: "127 min",
    descripcion: "Un grupo de antiheroes y agentes rotos debe colaborar en misiones imposibles, llevando la ambiguedad moral al frente del universo Marvel."
  },
  {
    id: 42,
    titulo: "Los 4 Fantasticos: Primeros pasos",
    tipo: "pelicula",
    genero: ["Ciencia ficcion", "Aventura"],
    imagen: "assets/images/fantastic4.jpg",
    fecha: "2025",
    anio: 2025,
    direccion: "Matt Shakman",
    guion: "Josh Friedman, Eric Pearson, Jeff Kaplan, Ian Springer",
    reparto: ["Pedro Pascal", "Vanessa Kirby", "Joseph Quinn", "Ebon Moss-Bachrach"],
    duracion: "114 min",
    descripcion: "La primera familia de Marvel entra al UCM con una propuesta retrofuturista que apuesta por la exploracion, la ciencia y la dinamica de equipo."
  }
];

window.shows = shows;
